workflows:
  ios_kmp_test:
    name: iOS KMP Test
    scripts:
      - name: Install XcodeGen
        script: |
          brew install xcodegen
      - name: Build KMP XCFramework
        script: |
          chmod +x gradlew
          cd shared
          ../gradlew assembleSharedKitDebugXCFramework
          mkdir -p ../iosApp/Frameworks
          cp -R build/XCFrameworks/debug/sharedKit.xcframework ../iosApp/Frameworks/
      - name: Generate Xcode project
        script: |
          cd iosApp
          xcodegen generate --spec xcodegen.yml
      - name: Build iOS app for Simulator (Debug, no tests)
        script: |
          xcodebuild \
            -project "iosApp/iosApp.xcodeproj" \
            -scheme "iosApp" \
            -sdk iphonesimulator \
            -configuration Debug \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            build
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
