workflows:
  flutter-module-ios-build:
    name: Build Flutter Module
    environment:
      flutter: 3.27.4
      groups:
        - google_play
    scripts:
      - name: Install dependencies
        script: |
          cd fieldbook
          flutter pub get

      - name: Bump iOS deployment target to 15.5
        script: |
          cd fieldbook
          
          # 1) Podfile: ensure at least iOS 15.5
          if [ -f .ios/Podfile ]; then
            sed -i '' "s/platform :ios, .*/platform :ios, '15.5'/g" .ios/Podfile
          else
            cat > .ios/Podfile <<EOF
          platform :ios, '15.5'
          target 'Runner' do
            use_frameworks!
          end
          EOF
          fi
          
          # 2) Flutter-generated xcconfig: override to 15.5
          sed -i '' "s/IPHONEOS_DEPLOYMENT_TARGET = .*/IPHONEOS_DEPLOYMENT_TARGET = 15.5/" .ios/Flutter/Generated.xcconfig

      - name: Exclude arm64 for iOS Simulator
        script: |
          cd fieldbook/.ios
          
          sed -i '' "/flutter_additional_ios_build_settings(target)/a\\
              target.build_configurations.each do |config|\\
                # Exclude arm64 when building for iOS simulator\\
                config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'\\
              end
          " Podfile
          
          # debug
          cat Podfile
          
          pod install --repo-update
      - name: Build iOS Framework
        script: |
          cd fieldbook
          flutter build ios --debug --simulator --no-codesign
    artifacts:
      - fieldbook/build/ios/iphonesimulator/Runner.app
    publishing:
      email:
        recipients:
          - n.soldevilla@integratedbreeding.net
